### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by TheHossein** [SciML/AutoOptimize.jl#22]
Hello, 

This may be coming from my ignorance (not a programmer first) but ```] add AutoOptimize``` cannot find the package to install. I know the package is experimental; are we suppose to try to install it in any other way?

```(@v1.6) pkg> add AutoOptimize
    Updating registry at `C:\Users\hhagh\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: The following package names could not be resolved:
 * AutoOptimize (not found in project, manifest or registry)
```

**Comment by anandijain** [comment]
you can also do `add git_url` pointing directly to this repo

**Comment by ChrisRackauckas** [comment]
`]add https://github.com/SciML/AutoOptimize.jl`

**Comment by TheHossein** [comment]
Thank you.
